#ifndef __COLOUR_SCHEME_H__
#define __COLOUR_SCHEME_H__

#include <curses.h>

#define COLOUR_SCHEME_OUTPUT 1
#define COLOUR_SCHEME_INPUT 2

#define COLOUR_SCHEME_PRIMARY COLOR_RED
#define COLOUR_SCHEME_SECONDARY COLOR_GREEN

#endif
